#!/bin/tcsh -f
#echo $1
if($1 != "") then
	set fname = $1
else
	set fname = "mykey"
endif
#echo "fname = ",$fname
openssl genrsa  -out ${fname}.pri 1024
#openssl genrsa -des3 -out ${fname}.pri 1024    # need a passwd
openssl rsa -in ${fname}.pri -pubout -out ${fname}.pub
echo output : ${fname}.pri ${fname}.pub

